### ISSUE TITLE
Create a discussion instead of a note

### ISSUE THREAD

**Issue by MathieuPuech** [rx-ts/changesets-gitlab#16]
Instead of creating a note, it could be nice to create a discussion (thread) that can be resolved. You can prevent the merge request to be merged when you have a discussion but a note will not prevent this.

See https://docs.gitlab.com/ee/user/discussions/

On gitbeaker, the API is available in `MergeRequestDiscussions`

**Comment by JounQin** [comment]
Would, thank you very much for clarifying this, I didn't know about that before!

**Comment by MathieuPuech** [comment]
Yes, I will explain a little more. You have an option on GitLab Project to prevent Merge Requests to be merged before all thread are resolved. When this option is enabled, your merge button is disabled with a message explaining why:

![image](https://user-images.githubusercontent.com/9367152/133780745-ffc52cae-42b1-436f-8ac0-d8c0c1eadfd1.png)

You can activate this feature by going to Settings > General > Merge Requests > Merge checks >  [ ]  All discussions must be resolved.

When a note (a comment in the GitLab UI) is created, it does not prevent to merge since it's not an opened discussion. If a discussion (a thread) is created, it will prevent to merge before the discussion is resolved.

It's a good reminder for the users to check the changeset creation.

More information about the [discussion feature in GitLab documentation](https://docs.gitlab.com/ee/user/discussions/#prevent-merge-unless-all-threads-are-resolved)

**Comment by JounQin** [comment]
@MathieuPuech I just tried in my project, the comment API will also create a note by default, it is just the same. You need to comment the individual comment to start a thread, which needs to be resolved before merging.

![image](https://user-images.githubusercontent.com/8336744/142832380-efea8c70-c3f6-4e86-bf5c-71dc95c8874a.png)

I'm using GitLab Community Edition 12.5.5, which seems not having this functionality.

And I don't know how to start a thread via API directly without comment, but I raised #27 for review now, can you help to test?

See https://ci.codesandbox.io/status/rx-ts/changesets-gitlab/pr/27/builds/190551 for installation before releasing.

**Comment by JounQin** [comment]
Oh, it seems just working.

![image](https://user-images.githubusercontent.com/8336744/142834253-271a9ddd-84d6-46b9-8def-c2ba7c9ce1d3.png)

**Comment by MathieuPuech** [comment]
I checked the PR #27 and it seems to be what we need to achieve that
