### ISSUE TITLE
Add support for providing CI_JOB_TOKEN

### ISSUE THREAD

**Issue by HosseinAgha** [rx-ts/changesets-gitlab#22]
Using the current options lib users can only provide personal access token. I want to use the Gitlab's CI_JOB_TOKEN in my comment stage as it is much safer.  
According to [gitbeaker docs](https://github.com/jdalrymple/gitbeaker) the job token should be provided in another config.  
Can we add an option to provide a job token? Are you open to a PR on this?

**Comment by JounQin** [comment]
How to reference `CI_JOB_TOKEN` as `GITLAB_TOKEN` in `variables`?

**Comment by HosseinAgha** [comment]
Like this:  
```yml
variables:  
   GITLAB_TOKEN: "${CI_JOB_TOKEN}"
```

**Comment by JounQin** [comment]
> Like this:
> 
> ```yaml
> variables:  
>    GITLAB_TOKEN: "${CI_JOB_TOKEN}"
> ```

If you confirm it works, it can be added into README.

**Comment by HosseinAgha** [comment]
I'm actually using my PR code in a real-world project. (by using Github protocol)  
I'm using CI_JOB_TOKEN as NPM_TOKEN actually. As I mentioned in #23 JobToken access is still limited to Gitlab package registry so I cannot use it in the `comment` stage until a Gitlab Epic that adds fine-grained JobToken access gets resolved.

**Comment by JounQin** [comment]
OK, then it should be mentioned that the functionality is not ready for now in changeset.

**Comment by HosseinAgha** [comment]
Done
