### ISSUE TITLE
Duplicate branch error when there is already an MR exists

### ISSUE THREAD

**Issue by HosseinAgha** [rx-ts/changesets-gitlab#25]
I think the `switchToMaybeExistingBranch` logic is wrong as it checks for a very specific git phrase. We need to make it more general.

**Comment by JounQin** [comment]
The original logic is copied from `changeset` itself, and I personally didn't meet related issue before, can you describe it in details?

**Comment by HosseinAgha** [comment]
The issue is that every git version has a different wording for switching the branches. Previous logic was this:   

```ts
!stderr
    .toString()
    .includes(`Switched to a new branch '${branch}'`)
```

But it is like this in my version of the git: `Switched to branch '${branch}'`.  So I changed it to `.includes('Switched to')` to be safe in all scenarios.
I think the original logic was wrong though, As we should not look for _a new branch_ phrase after normal checkout.
