### ISSUE TITLE
These command should be silence  for secure safe

### ISSUE THREAD

**Issue by pmjhonwang** [rx-ts/changesets-gitlab#33]
https://github.com/rx-ts/changesets-gitlab/blob/1b3ec8eafaa9fb58ac444e1c873d2cb832f24e76/src/main.ts#L38-L42

https://github.com/actions/toolkit/blob/main/packages/exec/src/interfaces.ts#L13
https://github.com/actions/toolkit/blob/88062ec4731967e1d4d835dee48b663379430edc/packages/exec/src/toolrunner.ts#L457

**Comment by JounQin** [comment]
@pmjhonwang Thanks for advice, PR welcome.

**Comment by pmjhonwang** [comment]
> @pmjhonwang Thanks for advice, PR welcome.

https://github.com/rx-ts/changesets-gitlab/pull/34
